### ISSUE TITLE
Bus Stop Bug 04/27 11:53pm

### ISSUE THREAD

**Issue by ks-moss** [ks-moss/472-2023-G3#159]
![Screenshot 2023-04-27 at 11 42 18 PM](https://user-images.githubusercontent.com/100756184/235075652-d4180e6d-b13a-4654-a57e-c9a9f84a148a.png)

As you can see in the above, waiting time counter won't set back to 0.
Bus makes a stop for 10 cycle for default bus stop.
But the bug also makes a stop for 5 cycles for newly added bus stop .

FIle: BusStopSimulation.py

**Comment by GusEsplin** [comment]
The bug was caused during the creation of bus stop entities in the add bus stop on click function. The entities where being created at the position of road that was most recently clicked. The position of the road is always the center of that road, so all bus stop entities added with the button where placed in the center of the most recently clicked road. Additionally, on button press, the creation of the bus stop in the traffic system bus stop list was done correctly; based of the user selected position. This caused a mismatch of where buses would think the bus stop is, and where the bus stop was placed on the screen. This bug is fixed by the above pull request.
